### PR TITLE
Add version argument for validateHub

### PR DESCRIPTION
**Pull request by zxenia**
## Changes with this PR:

- Add command-line argument **version** to validateHub.py to allow users to specify against which schema version to run the validation
- New example usage: `python validateHub.py --json=example_v2.0.json --version=2.0`
- Schema verison by default set to 1.0
- Run ontology validation only for version 2.0 (because ontology validation relies on CURIEs and v1.0 takes URIs)
- Fix example files
- Fix a few bugs in old code related to switch to arrays instead of strings

### CODE REVIEW

**Comment by sitag** [comment]
@zxenia you are making too many api calls that are redundant. e.g. there are ~1000 datasets for ~100 references, but you end up making 1000 api calls. the calls should be cached. are you familiar with memoization pattern and can you apply it here?

**Comment by zxenia** [comment]
Hi @sitag ,
I can add the caching here (memory or sqlite db). Thanks!

**Comment by sitag** [comment]
@zxenia You just need to memoize - just simply do this: 

```
def api_call(x):
    return ...

class APIWithCache:
    def __init__(self):
        self.cache = dict()
    def __call__(self, x):
        if not x in self.cache: return api_call(x)
        else: return self.cache[x]

api_call2 = APIWithCache()

api_call2(x)
```

**Comment by dzerbino** [comment]
Hello @zxenia @sitag @dbujold ,

This PR has been lingering for a while now, what is its status? Is it urgent?

Cheers,

Daniel

**Comment by zxenia** [comment]
Hi @dzerbino ,
the issue is done and can be merged. But I prefer to cross-check with @dbujold first, and I will merge it after that.

**Pull request merged**
