### PR TITLE
Required 1 1 attributes

### PR DESCRIPTION
**Pull request by dzerbino**
Hello @juettemann and @sitag ,

Please find my suggestions regarding the minimum required attributes for 1.1 attributes. 

I also updated the 1.1 sample attributes to at least match the 1.0 requirements.

On the way I found some minor typos here and there, so I'm raising this to both your attentions. 

Cheers,

Daniel

### CODE REVIEW

**Comment by juettemann** [comment]
OK for me.

**Comment by sitag** [comment]
@dzerbino Do you tests for 1.1 we can add?

**Comment by dzerbino** [comment]
Sorry, come again?

**Comment by sitag** [comment]
@dzerbino Do you have xmls that should and should not validate against 1.1? So we know unexpected is happening in the validator

**Comment by dzerbino** [comment]
Sorry, no. @juettemann could you please create those?

**Pull request merged**
