### PR TITLE
Adding biological replicates to sample description

### PR DESCRIPTION
**Pull request by dzerbino**
Address issue #29

### CODE REVIEW

**Comment by sitag** [comment]
need to clarify that accession is epirr or is something else permitted?

**Comment by dzerbino** [comment]
Does EpiRR generate sample accessions?

**Comment by sitag** [comment]
I thought you meant the EpiRR accession for replicate sample. Do you mean the EGA/ENA accession for underlying sample instead? Would we accept other archives? I think the the matched epirr accession would be most useful - this also means we can validate it.

**Comment by juettemann** [comment]
I am confused. The accession in the sample is the one from the respective archive. New submissions do not have an IHEC accession (which I assume is the EpiRR accession).

**Comment by dzerbino** [comment]
Rebased to master (with new schema file locations)

**Comment by sitag** [comment]
Okay.. I assume we were continuing discussing this based on the call? ...so what is this id? I believe it should be EpiRR.

**Comment by dbujold** [comment]
If it's EpiRR, what happens if a data submitter pushes 2 biological replicates in the same release?

1- They'll have to submit metadata to EGA without "biological_replicates" property.

2- They will submit datasets to EpiRR to get an accession id.

3- They'll need to resubmit metadata to EGA to insert the EpiRR record id.

4- They'll need to update the EpiRR record to add the change.

**Comment by dzerbino** [comment]
OK, summarising this thread: there are no IHEC sample IDs and even if there were it would be a pain in the neck to handle in the submission process. 

Therefore, sample IDs should be IDs from the respective archives (EGA, etc). 

Is this a fair summary?

**Comment by dbujold** [comment]
That's how I see unless I missed something. Even using EGA ids, for instance, would require a double submission, as you'll first need to generate your sample ids, before updating them with other sample ids.

**Pull request merged**
