### PR TITLE
Fix not allowing histone NA for ChIP-Seq input

### PR DESCRIPTION
**Pull request by sitag**
Fix the experiment semantic check bug with size one lists 1
Fix not allowing histone NA for ChIP-Seq input

### CODE REVIEW

**Comment by dzerbino** [comment]
Dear @sitag ,

Good point, this would create problems. 

I am wondering whether it could be done in a more direct way, because classifying ChIP-Seq inputs as chromatin marks (as opposed to TF) is arbitrary. Note that the `experiment_type` is one of input, histone or TF. 

I think it would be cleaner to make the required attributes optional if `experiment_type == "ChIP-Seq Input"`, rather than adding `NA` as a histone mark.

Cheers,

Daniel

**Comment by sitag** [comment]
@dzerbino The target_tf right now is required. It does not have a controlled vocabulary so supports NA. To treat both equally we should support NA for histone too. I can update the semantic check to test for both of them being NA for ChIP Input,

**Comment by dzerbino** [comment]
Hello @sitag ,

Would it not be simpler to state that if the experiment type is Input, then target_tf and target_histone should not be provided? I'm not a big fan of having a hard-coded 'NA' value, when it would be cleaner and simple to not define these attributes at all. 

Cheers,

Daniel

**Comment by sitag** [comment]
@dzerbino That's how ChIP-Input was setup earlier. Then @dbujold requsted that ChIP-Input and ChIP be coalesced with NA for not used items. Now spec requires them all https://github.com/IHEC/ihec-ecosystems/blob/master/schemas/json/2.0/experiment.json#L121-L147 
Making anything optional breaks that scheme.

**Comment by dzerbino** [comment]
OK, fair enough.

**Pull request merged**
