### PR TITLE
Feb2020 dz

### PR DESCRIPTION
**Pull request by dzerbino**
Hello guys,

Please find a proposed merged branch.

Regards,

Daniel

### CODE REVIEW

**Comment by dzerbino** [comment]
Sorry, Thomas could you please do that?

**Comment by juettemann** [comment]
Sure.
How do I pull in the changes from this pull request into my local feb2020 branch? Never done that.

**Comment by juettemann** [comment]
Done, looks all as expected.

**Comment by sitag** [comment]
@dzerbino unless there's a rush on getting the merge, I would add tests here. @zxenia can you also add tests for json hub validator part so we can catch any issues on merge?

**Comment by dzerbino** [comment]
Hello @sitag ,

I'm all in favour of tests, but I'm concerned that the EpiMap project requires us to send error reports to collaborators last January.

Considering that the priority at present is the XML validator and that we do have tests for that, could we not move to merge this branch, and make a point of pushing for tests on the JSON validator in parallel?

Cheers,

Daniel

**Comment by sitag** [comment]
@dzerbino okay.. merged.

**Pull request merged**
