### PR TITLE
Refatoring, busgfixes. Donor not working yet

### PR DESCRIPTION
**Pull request by juettemann**
Testrun with missing DONOR attributes pass, seems like allof is not recognised in combination with required.

### CODE REVIEW

**Comment by ilsley** [comment]
The problem with donor is addressed in pull request #88. This should be reviewed first.

**Comment by dzerbino** [comment]
In that case, could we just delete this PR (ie. #85)?

**Comment by juettemann** [comment]
It is easier to keep this request and add the changes #88. 
As far as I can see I addressed everything except the biomaterial_type and change curie to uri, which are only 6 lines. This request contains the same adjustments to donor, the issue that it is not working is, as far as I can see, the way it is implemented, not the array issue addressed here. In addition to correcting several required sections, ordering them to make checking the easier, adding descriptions, the code is now also much more readable. Redoing all this will take a while, whereby changing the 6 lines should be relatively fast.

**Comment by sitag** [comment]
@juettemann can we get donor to work in this request before merging? it's also time we hook in a proper testbench so we can reference what bugs are fixed.

**Comment by sitag** [comment]
@juettemann we can always replicate donor inside each biomaterial type for now and come back to it once we have 1.0 validated.

**Comment by juettemann** [comment]
@sitag The donor is corrected in the sample. Either the issue is within the validator code, or the structure of the sample is incorrect. Replicating the donor is also what I will try today, should be done in the next 4-5 hours.

**Comment by juettemann** [comment]
Created new branch from master, tj_json_schema_update, deleting this one

**Pull request closed without merging**
