### PR TITLE
Requiring input experiements for all ChIP-Seq experiments

### PR DESCRIPTION
**Pull request by dzerbino**
Hello, 

As requested by Martin and Sita, I have added a required attribute in ChIP-Seq experiments, namely a link to the input experiment. 

Cheers,

Daniel

### CODE REVIEW

**Comment by sitag** [comment]
@dzerbino I dont think adding the identifier to experiment metadata works - you may not have accession at the submission time, and validating aliases may not be possible. The information regarding the matched control should be provided at the epirr registration step as part of epirr metadata, and not part of experiment metadata.

**Comment by dzerbino** [comment]
Hello @sitag ,

Thanks for the feedback, that's a very good point. The problem is that we do not really collect EpiRR metadata, just a bunch of archive IDs. This is quite a conundrum...

Cheers,

Daniel

**Comment by sitag** [comment]
@dzerbino We just need one additional string field for epirr schema where we can store a json blob whose schema can be extended. perhaps an existing field used in epirr submission can be used this way.

**Comment by dzerbino** [comment]
Hello @sitag ,

Sorry, just back from holidays. You are right, control dependencies can only be declared at the EpiRR stage. 

At present we have sufficiently few submitters that we can simply ask them to send us an ancillary tab delimited file (by email if needed) but we should include this when we re-work the EpiRR APIs. 

Cheers,

Daniel

**Pull request closed without merging**
