### PR TITLE
UMI support + misc

### PR DESCRIPTION
**Pull request by sitag**
- Add UMI attributes
- Fix with leftover encoding issues
- Add dev schema support
- Add `__init__.py`

Still to add: umi string validation

### CODE REVIEW

**Comment by dzerbino** [comment]
Hello @sitag , 
In future could you create the new dev branch in a separate Pull Request? At present the diffs only show entirely new file, making review more complicated. 
Cheers,
Daniel

**Review by dzerbino — APPROVED** [review]
Looks good to me, assuming it is compatible with EGA standards. 

In future, could you please create the dev API branch on a separate PR? It would make things easier to review.

**Review by juettemann — CHANGES_REQUESTED** [review]
As @dzerbino already mentioned, there are too many different  issues in this PR. Going thoroughly through them would take a while.
With regard to Curie validation: At the moment I only see "ncit:C115935xxxxxxxxx" as a test. The most common mistake is having a URI instead of a curie, hence that should be tested. 
Second, there can be multiple curies in the same field (CL:0000096;UBERON:0013756), which should also be tested.

**Comment by sitag** [comment]
> As @dzerbino already mentioned, there are too many different issues in this PR. Going thoroughly through them would take a while.
> With regard to Curie validation: At the moment I only see "ncit:C115935xxxxxxxxx" as a test. The most common mistake is having a URI instead of a curie, hence that should be tested.
> Second, there can be multiple curies in the same field (CL:0000096;UBERON:0013756), which should also be tested.

Only last three commits address curie validation.  This CL:0000096;UBERON:0013756 will fail validation as you can check. We can add a check to identify uris. Right now we only do what @zxenia validator does.

**Review by juettemann — APPROVED** [review]

**Review by juettemann — CHANGES_REQUESTED** [review]
Apologies, still testing this I was mistaken by the UMI title, I forgot that this is basically everything that has been done in the past month.

**Review by juettemann — APPROVED** [review]

**Pull request closed without merging**
