### PR TITLE
Created basic SOP

### PR DESCRIPTION
**Pull request by dzerbino**
In response to #38

### CODE REVIEW

**Comment by sitag** [comment]
SOP for what? Once we have other SOPs this gets confusing?

**Comment by dzerbino** [comment]
This SOP is titled 'Submitting an update PR', and would be in the readme file, alongside any other SOP we decide to add.

**Comment by sitag** [comment]
@dzerbino Sorry.. didnt look at the second commit. Good to go by me.

**Comment by dzerbino** [comment]
Good idea! I'll modify it shortly.

**Pull request merged**
