### PR TITLE
Moved all the Portal and XML validators into a central location

### PR DESCRIPTION
**Pull request by dzerbino**

### CODE REVIEW

**Comment by dzerbino** [comment]
I did make an effort to update links/config files, but do let me know if I forgot anything. Cheers,

Daniel

**Comment by dzerbino** [comment]
Linked to #44

**Comment by sitag** [comment]
@dzerbino all the moves will break validators, cant merge till all breakages are fixed. 
@dbujold can you check the ihec data hub validator for breakages. i will look at xml validator. please push changes to this branch.

**Comment by sitag** [comment]
@zxenia @dbujold Can we try to merge the refactoring out the json validation error logging into request as well, since you guys will have to test the validators here anyway?

**Comment by dzerbino** [comment]
I have now fixed and tested both the portal and XML validators. 

As a note in passing, having paths hard coded into the source is rather naughty... 

Also, would it be possible to use relative paths when referencing a JSON file from another JSON file? Currently the paths are relative to PWD which is not practical.

**Pull request merged**
