### PR TITLE
Added requests library to avoid dependency errors.

### PR DESCRIPTION
**Pull request by DavidBrownlee**

### CODE REVIEW

**Comment by sitag** [comment]
sorry, where is requests used in the source?

**Comment by DavidBrownlee** [comment]
urllib3 and chardet seem to be related to this requests library.  The validateHub.py script generated a warning (I believe it was a RequestsDependencyWarning) until the requests library was included.

While `pip show urllib3` and `pip show chardet` do not list any dependencies for these 2 libraries, `pip show requests` returns:
Name: requests
Version: 2.22.0
Summary: Python HTTP for Humans.
Home-page: http://python-requests.org
Author: Kenneth Reitz
Author-email: me@kennethreitz.org
License: Apache 2.0
Location: /home/dbrownlee/.local/lib/python3.6/site-packages
Requires: chardet, idna, certifi, urllib3

There is some relation between the three.

I do find this rather strange. Your call on whether to include this Pull Request, I'm just saying that including the requests library solved a warning on this system.  It could all be a matter of version conflicts though...

**Comment by sitag** [comment]
`requests` is never directly imported. you never listed the actual warning. but i will assume it's this: https://stackoverflow.com/questions/50202238/requestsdependencywarning-urllib3-1-9-1-or-chardet-2-3-0-doesnt-match-a-su seems to say that this is optionally fixed by having the correct version of urllib3 and chardet. since `requests` is not a direct dependency, it's doesn't seem to make sense to force people to install a module when the warning may be indicative of something else wrong with the setup. we can revisit this if there's a bug report filed.

**Comment by sitag** [comment]
@zxenia your call.

**Comment by DavidBrownlee** [comment]
I agree that forcing the inclusion of a library that isn't used (present only for dependency reasons) is against good practices.  The actual error/warning I received was something other than the stackoverflow link, but similar.
Since the error/warning can be solved through some googling and may be more indicative of my system (just recently configured) than something general, how about I just withdraw this pull request.
Thanks for your comments.

**Comment by DavidBrownlee** [comment]
PR closed.

**Pull request closed without merging**
